---
driver:
  name: vagrant
  customize:
    cpus: 8
    memory: 4096


provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[et_java::default]
